#!/bin/bash

if [ ! -d ${HOME}/.oh-my-zsh ]; then
	read -p "oh-my-zsh not found - install? [Yn] " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]?$ ]]; then
		sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
		
		\mv .zshrc.pre-oh-my-zsh .zshrc
	fi
fi

if [ ! -d ${HOME}/.vim/bundle/Vundle.vim ]; then
	read -p "Vundle.vim not found - install? [yn] " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]?$ ]]; then
		mkdir -p ${HOME}/.vim/bundle && \
			git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
	fi
fi

if [ ! -d ${HOME}/.zsh-plugins ]; then
	read -p "Clone zsh plusing? [yn] " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]?$ ]]; then
		mkdir -p ${HOME}/.zsh-plugins && \
			git clone https://github.com/zdharma/fast-syntax-highlighting ${HOME}/.zsh-plugins/fsh
	fi
fi

echo "Installing package selection..."

if [ -x /usr/sbin/pacman ]; then
	sudo pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort ~/.config/yadm/pkglist-pacman.txt))

	read -p "Install KDE packages? [Yn] " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]?$ ]]; then
		sudo pacman -S --needed $(comm -12 <(pacman -Slq | sort) <(sort ~/.config/yadm/pkglist-pacman-kde.txt))
	fi
fi

if [ -x /usr/sbin/yay ]; then
	echo "Install aur packages like this:"
	echo -e "    yay -S --needed - <(sort ~/.config/yadm/pkglist-aur.txt)"
fi

if [ -x /usr/bin/apt-get ]; then
	sort ~/.config/yadm/pkglist-apt.txt | xargs sudo apt-get install
fi
