#!/bin/bash

function ask_yes {
	read -p "$1 [Yn] " -n 1 -r
	echo
	if [[ $REPLY =~ ^[Yy]?$ ]]; then
		return 0
	else
		return 1
	fi
}

if [ -x /usr/bin/apt-get ]; then
	ask_yes "Install package selection?" && \
		sort ~/.config/yadm/pkglist.txt | xargs sudo apt-get install -y
fi

if [ -x /usr/bin/dnf ]; then
	ask_yes "Install package selection?" && \
		sort ~/.config/yadm/pkglist.txt | xargs sudo dnf install -y
fi

echo "Updating font-cache..."
fc-cache -fv
